I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 42, in script
    Turandot "Oh, I'm just stuck here. My name's Turandot."
Exception: Sayer 'Turandot' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 42, in script
    Turandot "Oh, I'm just stuck here. My name's Turandot."
  File "C:\Users\Karely\Desktop\renpy-8.3.2-sdk\renpy\ast.py", line 2573, in execute
    Say.execute(self)
  File "C:\Users\Karely\Desktop\renpy-8.3.2-sdk\renpy\ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Karely\Desktop\renpy-8.3.2-sdk\renpy\ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'Turandot' is not defined.

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.2.24090902
O Coco Taco The Visual Novel The Game 1.0
Mon Feb  3 15:26:35 2025
